services:
     lmdi.alphasort.listener:
        class: lmdi\alphasort\event\listener
        arguments:
            - '@dbal.conn'
            - '@template'
            - '@cache'
            - '@user'
            - '@request'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
